<a href="https://colab.research.google.com/github/May-o-nnaise/CPSMA-4313-MS/blob/main/DataVizQuiz18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Quiz 18

In [3]:
import pandas as pa
import datetime as datetime

df = pa.read_csv("https://raw.githubusercontent.com/nurfnick/Data_Viz/main/Data_Sets/IOT-temp.csv")
df.head(10)

,id,room_id/id,noted_date,temp,out/in
0,__export__.temp_log_196134_bd201015,Room Admin,08-12-2018 09:30,29,In
1,__export__.temp_log_196131_7bca51bc,Room Admin,08-12-2018 09:30,29,In
2,__export__.temp_log_196127_522915e3,Room Admin,08-12-2018 09:29,41,Out
3,__export__.temp_log_196128_be0919cf,Room Admin,08-12-2018 09:29,41,Out
4,__export__.temp_log_196126_d30b72fb,Room Admin,08-12-2018 09:29,31,In
5,__export__.temp_log_196125_b0fa0b41,Room Admin,08-12-2018 09:29,31,In
6,__export__.temp_log_196121_01544d45,Room Admin,08-12-2018 09:28,29,In
7,__export__.temp_log_196122_f8b80a9f,Room Admin,08-12-2018 09:28,29,In
8,__export__.temp_log_196111_6b7a0848,Room Admin,08-12-2018 09:26,29,In
9,__export__.temp_log_196112_e134aebd,Room Admin,08-12-2018 09:26,29,In

##Convert the noted_date into DateTime, it is in day-month-Year Hour:Minute format.

In [5]:
pa.to_datetime(df.noted_date, format='%d-%m-%Y %H:%M')

0       2018-12-08 09:30:00
1       2018-12-08 09:30:00
2       2018-12-08 09:29:00
3       2018-12-08 09:29:00
4       2018-12-08 09:29:00
                ...
97601   2018-07-28 07:07:00
97602   2018-07-28 07:07:00
97603   2018-07-28 07:06:00
97604   2018-07-28 07:06:00
97605   2018-07-28 07:06:00
Name: noted_date, Length: 97606, dtype: datetime64[ns]

##What is the minimum and maximum date and time?

In [11]:
df['noted_date'] = pa.to_datetime(df.noted_date, format='%d-%m-%Y %H:%M')
print(f"Minimum Date: {df['noted_date'].min()}")
print(f"Maximum Date: {df['noted_date'].max()}")

Minimum Date: 2018-07-28 07:06:00
Maximum Date: 2018-12-08 09:30:00

take the dable and grab print the minimum and maximum

##What is the largest interval inbetween temperature checks?

In [18]:
df['noted_date'] = pa.to_datetime(df.noted_date, format='%d-%m-%Y %H:%M')
largest_interval = df['noted_date'].sort_values().diff().max()
print(f"Largest Interval between temperature checks: {largest_interval}")

Largest Interval between temperature checks: 11 days 13:38:00

this sorts the values by difference and takes the maximum difference.

##What is the average datetime?

In [59]:
avg_datetime = df['noted_date'].mean()
print(f"Average Datetime: {pa.to_datetime(avg_datetime)}")

Average Datetime: 2018-10-07 05:10:38.821178880

take the table and just take the mean of the date

##What was the average outside temperature on '09-11-2018'?

In [41]:
df['noted_date'] = pa.to_datetime(df.noted_date, format='%m-%d-%Y')
date_to_filter = '09-11-2018'

filtered_df = df[(df['noted_date'].dt.date == pa.to_datetime(date_to_filter).date()) & (df['out/in'] == 'Out')]
average_outside_temp = filtered_df['temp'].mean()
print(f"Average outside temperature on {date_to_filter}: {average_outside_temp}")

Average outside temperature on 09-11-2018: 30.057547040241726

Take the dataframe and format it to how the date is on the question. Select the date and make a new dataframe where its just the speciffied date and only the rows where its outside temp. Grab the mean from that and then print it.