In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

#Quiz 10

##1. What was the second most popular starting station?

In [ ]:

%%bigquery --project dataviz-488505

WITH table as (
SELECT COUNT(*) as number_trips, start_station_name
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
GROUP BY start_station_name
ORDER BY number_trips DESC
LIMIT 2
)

SELECT number_trips
FROM table
WHERE number_trips = (SELECT MIN(number_trips) FROM table)

Query is running:   0%|          |

Downloading:   0%|          |

   number_trips
0         71145

There you have it. I used the method we talked about where you limit it by 2 and then you grab the minimum. I didn't end up doing the thing where you take the descending order and then limit it again I thought this mightve been easier which it was.

##

##2. How many trips lasted over an hour and were a round trip (started and stopped at the same station)?

In [ ]:
%%bigquery --project dataviz-488505

WITH table2 as (
SELECT start_station_name, duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
WHERE start_station_name = end_station_name
LIMIT 100
)

SELECT COUNT(*) as number_trips
FROM table2
WHERE duration_minutes > 60

Query is running:   0%|          |

Downloading:   0%|          |

   number_trips
0            21

This one also wasn't too bad. I think I probably didnt have to make this a table as well but making things tables actually makes stuff a lot easier than writing all this extra stuff in the previous functions and calls. Now I can just count everything from the table where its just greater than 60 minutes